package cn.vove7.common.datamanager.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.vove7.common.datamanager.parse.model.ActionDesc;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACTION_DESC".
*/
public class ActionDescDao extends AbstractDao<ActionDesc, Long> {

    public static final String TABLENAME = "ACTION_DESC";

    /**
     * Properties of entity ActionDesc.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Instructions = new Property(1, String.class, "instructions", false, "INSTRUCTIONS");
        public final static Property Example = new Property(2, String.class, "example", false, "EXAMPLE");
    }


    public ActionDescDao(DaoConfig config) {
        super(config);
    }
    
    public ActionDescDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACTION_DESC\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"INSTRUCTIONS\" TEXT," + // 1: instructions
                "\"EXAMPLE\" TEXT);"); // 2: example
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACTION_DESC\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ActionDesc entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String instructions = entity.getInstructions();
        if (instructions != null) {
            stmt.bindString(2, instructions);
        }
 
        String example = entity.getExample();
        if (example != null) {
            stmt.bindString(3, example);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ActionDesc entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String instructions = entity.getInstructions();
        if (instructions != null) {
            stmt.bindString(2, instructions);
        }
 
        String example = entity.getExample();
        if (example != null) {
            stmt.bindString(3, example);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ActionDesc readEntity(Cursor cursor, int offset) {
        ActionDesc entity = new ActionDesc( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // instructions
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // example
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ActionDesc entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setInstructions(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setExample(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ActionDesc entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ActionDesc entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ActionDesc entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
