package cn.vove7.common.datamanager.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.vove7.common.datamanager.parse.model.Action;
import cn.vove7.common.datamanager.parse.model.ActionScope;
import cn.vove7.common.datamanager.parse.statusmap.ActionNode;
import cn.vove7.common.datamanager.parse.statusmap.Reg;
import cn.vove7.common.datamanager.AppAdInfo;
import cn.vove7.common.datamanager.executor.entity.MarkedData;
import cn.vove7.common.datamanager.parse.model.ActionDesc;
import cn.vove7.common.datamanager.InstSettings;

import cn.vove7.common.datamanager.greendao.ActionDao;
import cn.vove7.common.datamanager.greendao.ActionScopeDao;
import cn.vove7.common.datamanager.greendao.ActionNodeDao;
import cn.vove7.common.datamanager.greendao.RegDao;
import cn.vove7.common.datamanager.greendao.AppAdInfoDao;
import cn.vove7.common.datamanager.greendao.MarkedDataDao;
import cn.vove7.common.datamanager.greendao.ActionDescDao;
import cn.vove7.common.datamanager.greendao.InstSettingsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig actionDaoConfig;
    private final DaoConfig actionScopeDaoConfig;
    private final DaoConfig actionNodeDaoConfig;
    private final DaoConfig regDaoConfig;
    private final DaoConfig appAdInfoDaoConfig;
    private final DaoConfig markedDataDaoConfig;
    private final DaoConfig actionDescDaoConfig;
    private final DaoConfig instSettingsDaoConfig;

    private final ActionDao actionDao;
    private final ActionScopeDao actionScopeDao;
    private final ActionNodeDao actionNodeDao;
    private final RegDao regDao;
    private final AppAdInfoDao appAdInfoDao;
    private final MarkedDataDao markedDataDao;
    private final ActionDescDao actionDescDao;
    private final InstSettingsDao instSettingsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        actionDaoConfig = daoConfigMap.get(ActionDao.class).clone();
        actionDaoConfig.initIdentityScope(type);

        actionScopeDaoConfig = daoConfigMap.get(ActionScopeDao.class).clone();
        actionScopeDaoConfig.initIdentityScope(type);

        actionNodeDaoConfig = daoConfigMap.get(ActionNodeDao.class).clone();
        actionNodeDaoConfig.initIdentityScope(type);

        regDaoConfig = daoConfigMap.get(RegDao.class).clone();
        regDaoConfig.initIdentityScope(type);

        appAdInfoDaoConfig = daoConfigMap.get(AppAdInfoDao.class).clone();
        appAdInfoDaoConfig.initIdentityScope(type);

        markedDataDaoConfig = daoConfigMap.get(MarkedDataDao.class).clone();
        markedDataDaoConfig.initIdentityScope(type);

        actionDescDaoConfig = daoConfigMap.get(ActionDescDao.class).clone();
        actionDescDaoConfig.initIdentityScope(type);

        instSettingsDaoConfig = daoConfigMap.get(InstSettingsDao.class).clone();
        instSettingsDaoConfig.initIdentityScope(type);

        actionDao = new ActionDao(actionDaoConfig, this);
        actionScopeDao = new ActionScopeDao(actionScopeDaoConfig, this);
        actionNodeDao = new ActionNodeDao(actionNodeDaoConfig, this);
        regDao = new RegDao(regDaoConfig, this);
        appAdInfoDao = new AppAdInfoDao(appAdInfoDaoConfig, this);
        markedDataDao = new MarkedDataDao(markedDataDaoConfig, this);
        actionDescDao = new ActionDescDao(actionDescDaoConfig, this);
        instSettingsDao = new InstSettingsDao(instSettingsDaoConfig, this);

        registerDao(Action.class, actionDao);
        registerDao(ActionScope.class, actionScopeDao);
        registerDao(ActionNode.class, actionNodeDao);
        registerDao(Reg.class, regDao);
        registerDao(AppAdInfo.class, appAdInfoDao);
        registerDao(MarkedData.class, markedDataDao);
        registerDao(ActionDesc.class, actionDescDao);
        registerDao(InstSettings.class, instSettingsDao);
    }
    
    public void clear() {
        actionDaoConfig.clearIdentityScope();
        actionScopeDaoConfig.clearIdentityScope();
        actionNodeDaoConfig.clearIdentityScope();
        regDaoConfig.clearIdentityScope();
        appAdInfoDaoConfig.clearIdentityScope();
        markedDataDaoConfig.clearIdentityScope();
        actionDescDaoConfig.clearIdentityScope();
        instSettingsDaoConfig.clearIdentityScope();
    }

    public ActionDao getActionDao() {
        return actionDao;
    }

    public ActionScopeDao getActionScopeDao() {
        return actionScopeDao;
    }

    public ActionNodeDao getActionNodeDao() {
        return actionNodeDao;
    }

    public RegDao getRegDao() {
        return regDao;
    }

    public AppAdInfoDao getAppAdInfoDao() {
        return appAdInfoDao;
    }

    public MarkedDataDao getMarkedDataDao() {
        return markedDataDao;
    }

    public ActionDescDao getActionDescDao() {
        return actionDescDao;
    }

    public InstSettingsDao getInstSettingsDao() {
        return instSettingsDao;
    }

}
