package cn.vove7.common.datamanager.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.vove7.common.datamanager.executor.entity.MarkedContact;
import cn.vove7.common.datamanager.executor.entity.MarkedOpen;
import cn.vove7.common.datamanager.parse.model.Action;
import cn.vove7.common.datamanager.parse.model.ActionScope;
import cn.vove7.common.datamanager.parse.statusmap.ActionNode;
import cn.vove7.common.datamanager.parse.statusmap.Reg;
import cn.vove7.common.datamanager.AppAdInfo;

import cn.vove7.common.datamanager.greendao.MarkedContactDao;
import cn.vove7.common.datamanager.greendao.MarkedOpenDao;
import cn.vove7.common.datamanager.greendao.ActionDao;
import cn.vove7.common.datamanager.greendao.ActionScopeDao;
import cn.vove7.common.datamanager.greendao.ActionNodeDao;
import cn.vove7.common.datamanager.greendao.RegDao;
import cn.vove7.common.datamanager.greendao.AppAdInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig markedContactDaoConfig;
    private final DaoConfig markedOpenDaoConfig;
    private final DaoConfig actionDaoConfig;
    private final DaoConfig actionScopeDaoConfig;
    private final DaoConfig actionNodeDaoConfig;
    private final DaoConfig regDaoConfig;
    private final DaoConfig appAdInfoDaoConfig;

    private final MarkedContactDao markedContactDao;
    private final MarkedOpenDao markedOpenDao;
    private final ActionDao actionDao;
    private final ActionScopeDao actionScopeDao;
    private final ActionNodeDao actionNodeDao;
    private final RegDao regDao;
    private final AppAdInfoDao appAdInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        markedContactDaoConfig = daoConfigMap.get(MarkedContactDao.class).clone();
        markedContactDaoConfig.initIdentityScope(type);

        markedOpenDaoConfig = daoConfigMap.get(MarkedOpenDao.class).clone();
        markedOpenDaoConfig.initIdentityScope(type);

        actionDaoConfig = daoConfigMap.get(ActionDao.class).clone();
        actionDaoConfig.initIdentityScope(type);

        actionScopeDaoConfig = daoConfigMap.get(ActionScopeDao.class).clone();
        actionScopeDaoConfig.initIdentityScope(type);

        actionNodeDaoConfig = daoConfigMap.get(ActionNodeDao.class).clone();
        actionNodeDaoConfig.initIdentityScope(type);

        regDaoConfig = daoConfigMap.get(RegDao.class).clone();
        regDaoConfig.initIdentityScope(type);

        appAdInfoDaoConfig = daoConfigMap.get(AppAdInfoDao.class).clone();
        appAdInfoDaoConfig.initIdentityScope(type);

        markedContactDao = new MarkedContactDao(markedContactDaoConfig, this);
        markedOpenDao = new MarkedOpenDao(markedOpenDaoConfig, this);
        actionDao = new ActionDao(actionDaoConfig, this);
        actionScopeDao = new ActionScopeDao(actionScopeDaoConfig, this);
        actionNodeDao = new ActionNodeDao(actionNodeDaoConfig, this);
        regDao = new RegDao(regDaoConfig, this);
        appAdInfoDao = new AppAdInfoDao(appAdInfoDaoConfig, this);

        registerDao(MarkedContact.class, markedContactDao);
        registerDao(MarkedOpen.class, markedOpenDao);
        registerDao(Action.class, actionDao);
        registerDao(ActionScope.class, actionScopeDao);
        registerDao(ActionNode.class, actionNodeDao);
        registerDao(Reg.class, regDao);
        registerDao(AppAdInfo.class, appAdInfoDao);
    }
    
    public void clear() {
        markedContactDaoConfig.clearIdentityScope();
        markedOpenDaoConfig.clearIdentityScope();
        actionDaoConfig.clearIdentityScope();
        actionScopeDaoConfig.clearIdentityScope();
        actionNodeDaoConfig.clearIdentityScope();
        regDaoConfig.clearIdentityScope();
        appAdInfoDaoConfig.clearIdentityScope();
    }

    public MarkedContactDao getMarkedContactDao() {
        return markedContactDao;
    }

    public MarkedOpenDao getMarkedOpenDao() {
        return markedOpenDao;
    }

    public ActionDao getActionDao() {
        return actionDao;
    }

    public ActionScopeDao getActionScopeDao() {
        return actionScopeDao;
    }

    public ActionNodeDao getActionNodeDao() {
        return actionNodeDao;
    }

    public RegDao getRegDao() {
        return regDao;
    }

    public AppAdInfoDao getAppAdInfoDao() {
        return appAdInfoDao;
    }

}
