package cn.vove7.common.datamanager.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.vove7.common.datamanager.executor.entity.MarkedOpen;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MARKED_OPEN".
*/
public class MarkedOpenDao extends AbstractDao<MarkedOpen, Long> {

    public static final String TABLENAME = "MARKED_OPEN";

    /**
     * Properties of entity MarkedOpen.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, String.class, "key", false, "KEY");
        public final static Property Type = new Property(2, String.class, "type", false, "TYPE");
        public final static Property RegStr = new Property(3, String.class, "regStr", false, "REG_STR");
        public final static Property Value = new Property(4, String.class, "value", false, "VALUE");
    }


    public MarkedOpenDao(DaoConfig config) {
        super(config);
    }
    
    public MarkedOpenDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MARKED_OPEN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"KEY\" TEXT NOT NULL ," + // 1: key
                "\"TYPE\" TEXT," + // 2: type
                "\"REG_STR\" TEXT," + // 3: regStr
                "\"VALUE\" TEXT);"); // 4: value
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_MARKED_OPEN_KEY ON \"MARKED_OPEN\"" +
                " (\"KEY\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MARKED_OPEN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MarkedOpen entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getKey());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String regStr = entity.getRegStr();
        if (regStr != null) {
            stmt.bindString(4, regStr);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(5, value);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MarkedOpen entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getKey());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(3, type);
        }
 
        String regStr = entity.getRegStr();
        if (regStr != null) {
            stmt.bindString(4, regStr);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(5, value);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MarkedOpen readEntity(Cursor cursor, int offset) {
        MarkedOpen entity = new MarkedOpen( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // key
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // regStr
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // value
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MarkedOpen entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getString(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRegStr(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setValue(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MarkedOpen entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MarkedOpen entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MarkedOpen entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
